spring.application.name=spring-vulnerable-lab
spring.profiles.active=dev
server.port=8081

jwt.segredo=${JWT_SEGREDO:scredo-jwt-trabalho}
jwt.expiracao-ms=86400000

cors.origens-permitidas=http://localhost:3000,http://localhost:8081,http://127.0.0.1:3000

limite.requisicoes-por-minuto=60

server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-exception=false
